export const COPY = Object.freeze({
  appTitle: '규칙 단위 기관실',
  cellSuffix: '칸',
  shapeSuffix: '모양',
  originalTokenSuffix: '원래 항',
  emptyCellLabel: '빈칸',
  patternBoardLabel: '규칙 배열',
  startAction: '운행 시작',
  settingsAction: '접근성 설정',
  startTitle: '기관실 문을 열어 볼까요?',
  startInstruction: '모양의 반복 규칙을 찾아 다섯 가지 미션을 해 봐요.',
  findTitle: '한 묶음 찾기',
  continueTitle: '다음 칸 이어 붙이기',
  findSubmit: '한 묶음 찾기',
  continueSubmit: '이어 붙이기',
  repairTitle: '규칙 수리하기',
  repairChoicesLabel: '새 모양 선택',
  repairSubmit: '고치기',
  repairSuccess: '규칙을 깨뜨린 칸을 고쳤어요.',
  retryWrongPosition: '규칙을 깨뜨린 칸을 다시 찾아봐요.',
  retryWrongReplacement: '선택한 칸에 들어갈 모양을 다시 골라요.',
  translateTitle: '새 모양으로 바꾸기',
  translationSourceLabel: '바꿀 원래 항',
  translationTargetLabel: '새 모양 선택',
  translateSubmit: '같은 규칙 확인',
  translateSuccess: '모양은 달라도 같은 순서예요.',
  retryMappingNotBijective: '서로 다른 항에는 서로 다른 새 모양을 골라요.',
  retryOrderChanged: '새 모양의 순서를 다시 살펴봐요.',
  retryMissingMapping: '각 원래 항에 새 모양을 하나씩 골라요.',
  translatedBoardLabel: '바꾼 규칙 배열',
  translationPairsLabel: '고른 대응',
  progressLabel: '현재 단계',
  nextStageSectionLabel: '다음 학습 단계',
  nextStage: '다음 칸',
  nextContinueStage: '다음 활동: 이어 붙이기',
  nextRepairStage: '다음 활동: 규칙 수리하기',
  nextTranslateStage: '다음 활동: 새 모양으로 바꾸기',
  nextCreateStage: '다음 활동: 내 규칙 만들기',
  findHintAction: '테두리 도움 보기',
  findChoicesLabel: '후보 묶음 선택',
  continueChoicesLabel: '다음 칸 선택',
  candidatePrefix: '후보',
  unitCountOne: '한',
  unitCountTwo: '두',
  unitCountThree: '세',
  unitCountSuffix: '칸',
  findInstruction: '가장 짧게 되풀이되는 한 묶음을 골라요.',
  continueInstruction: '한 묶음을 보고 다음 칸을 이어 보세요.',
  repairInstruction: '규칙을 깨뜨린 칸을 찾아 고쳐요.',
  translateInstruction: '같은 순서를 새 모양으로 바꾸어 보세요.',
  createInstruction: '2~3개로 내 한 묶음을 만들어요.',
  retryNotShortest: '되풀이되지만 더 짧은 한 묶음이 있어요.',
  retryDoesNotRepeat: '이 묶음으로는 끝까지 되풀이되지 않아요.',
  findSuccess: '가장 짧은 한 묶음을 찾았어요.',
  continueSuccess: '한 묶음으로 다음 칸을 이었어요.',
  retryWrongContinuation: '한 묶음의 순서를 다시 살펴봐요.',
  hintUnitOutline: '테두리로 나눈 묶음을 차례로 살펴보세요.',
  needsSecondRepeat: '같은 묶음을 한 번 더 붙여 보세요.',
  strategyUsed: '테두리 도움을 사용해 규칙을 찾았어요.',
  complete: '찾고, 잇고, 고치고, 바꾸고, 만들었어요.',
  createTitle: '내 규칙 운행',
  createUnitTitle: '한 묶음 만들기',
  createTrackTitle: '반복 선로 만들기',
  createTokenChoices: '묶음에 넣을 모양',
  removeFreeToken: '마지막 모양 지우기',
  lockFreeUnit: '묶음 정하기',
  appendFreeUnit: '한 묶음 붙이기',
  freeTrackLimit: '선로는 12칸까지 만들 수 있어요.',
  resetFreePattern: '다시 만들기',
  runFreePattern: '운행하기',
  createSuccess: '내 규칙이 두 번 되풀이돼요.',
  retryUnitNeedsTwo: '두 가지 모양을 섞어 한 묶음을 만들어 보세요.',
  retryUnitLength: '한 묶음은 2~3칸으로 만들어요.',
  freeUnitBoardLabel: '내 한 묶음',
  freeTrackBoardLabel: '내 반복 선로',
  summaryTitle: '활동 도장',
  summaryTakeaway: '반복되는 한 묶음을 찾으면 다음 칸을 예측할 수 있어요.',
  summaryNextPrompt: '다음에는 다른 모양의 규칙도 찾아봐요.',
  summaryStampMarker: '✓',
  summaryListLabel: '완료한 학습 행동',
  nextJourney: '다음 운행',
  returnHome: '처음으로',
  strategySummary: '테두리 도움을 사용했어요.',
  evidenceUnit: '가장 짧은 한 묶음 찾기',
  evidenceContinue: '다음 항 이어 붙이기',
  evidenceRepair: '규칙을 깨뜨린 칸 고치기',
  evidenceTranslate: '다른 모습으로 같은 순서 만들기',
  evidenceCreate: '내 반복 규칙 만들기',
  audioListen: '안내 듣기',
  audioStop: '안내 멈추기',
  audioUnavailable: '음성이 없어도 글을 보며 계속할 수 있어요.',
  audioDisclosure: 'AI 합성 음성으로 만든 안내예요.',
  settingsOn: '켜짐',
  settingsOff: '꺼짐',
  settingsTitle: '접근성 설정',
  settingsClose: '설정 닫기',
  audioSetting: '안내 음성',
  motionSetting: '모션 줄이기',
  patternContrastSetting: '무늬 대비 높이기',
  persistenceSetting: '이 기기에서 이어 하기',
  storageExplanation: '운행 위치와 접근성 설정만 이 기기에 저장해요.',
  storageOffExplanation: '끄면 확인 후 이 앱의 저장 내용을 지워요.',
  persistenceOffTitle: '이어 하기 끄기 확인',
  persistenceOffMessage: '저장된 이어 하기 기록을 지울까요?',
  persistenceOffConfirm: '이어 하기 끄기',
  persistenceOffCancel: '계속 사용',
  systemMotionNotice: '기기에서 모션 줄이기를 켜면 함께 줄어들어요.',
  motionReducedNotice: '모션을 줄여서 보여 줘요.',
  motionDefaultNotice: '기본 모션으로 보여 줘요.',
} as const);

export const STAGE_META = Object.freeze({
  find: { title: COPY.findTitle, instruction: COPY.findInstruction },
  continue: { title: COPY.continueTitle, instruction: COPY.continueInstruction },
  repair: { title: COPY.repairTitle, instruction: COPY.repairInstruction },
  translate: { title: COPY.translateTitle, instruction: COPY.translateInstruction },
  create: { title: COPY.createTitle, instruction: COPY.createInstruction },
});

export type CopyKey = keyof typeof COPY;

export function formatTokenShape(label: string): string {
  return `${label} ${COPY.shapeSuffix}`;
}

export function formatOriginalToken(label: string): string {
  return `${label} ${COPY.originalTokenSuffix}`;
}

export function formatUnitChoice(labels: readonly string[]): string {
  const countWord = {
    1: COPY.unitCountOne,
    2: COPY.unitCountTwo,
    3: COPY.unitCountThree,
  }[labels.length] ?? String(labels.length);
  return `${labels.join(', ')} ${countWord} ${COPY.unitCountSuffix}`;
}

export function formatFindCandidate(index: number, labels: readonly string[]): string {
  return `${COPY.candidatePrefix} ${index + 1}: ${formatUnitChoice(labels)}`;
}
